# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0009_auto_20170912_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologies',
            name='Catalyst',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technologies',
            name='Operation_Time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
