# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0010_auto_20170912_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmatchingresources',
            name='Extraction',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
