# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0011_addmatchingresources_extraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmatchingresources',
            name='Matching_HS_Code',
            field=models.CharField(max_length=500),
        ),
    ]
