# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0013_addmatchingresources_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmatchingresources',
            name='Parameters',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addmatchingresources',
            name='Technology',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
