# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0014_auto_20170912_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmatchingresources',
            name='Parameters',
        ),
        migrations.RemoveField(
            model_name='addmatchingresources',
            name='Technology',
        ),
    ]
