# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0015_auto_20170912_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmatchingresources',
            name='Source',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresources',
            name='Method',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
