# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0016_auto_20170912_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmatchingresources',
            name='Format',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
