# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0017_auto_20170912_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='addresources',
            name='Parameters',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresources',
            name='Source',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
