# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0018_auto_20170919_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
