# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0019_delete_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresources',
            name='Method',
        ),
        migrations.RemoveField(
            model_name='addresources',
            name='Parameters',
        ),
        migrations.RemoveField(
            model_name='addresources',
            name='Source',
        ),
    ]
