# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0002_auto_20170617_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='addmatchingresources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Matching_Resource', models.CharField(max_length=500)),
                ('Matching_HS_Code', models.IntegerField()),
                ('Check_if_matches_interchangeable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='addresources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Resource', models.CharField(max_length=500)),
                ('HS_Code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='editresources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Resource', models.CharField(max_length=500)),
                ('HS_Code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Method', models.TextField()),
                ('Process', models.TextField()),
                ('Temperature', models.IntegerField()),
                ('Pressure', models.IntegerField()),
                ('Sample_Weight', models.IntegerField()),
                ('Catalyst', models.TextField()),
                ('Operation_Time', models.IntegerField()),
                ('add_matchingresources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.addmatchingresources')),
                ('add_resources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.addresources')),
            ],
        ),
        migrations.AddField(
            model_name='addmatchingresources',
            name='add_resources',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.addresources'),
        ),
    ]
